name: Docs Check

on:
  push:
  pull_request:

jobs:
  markdown-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify docs folder exists
        run: |
          test -d docs
          test -f README.md
